### ISSUE TITLE
Allowing a <list> element in the <front>?

### ISSUE THREAD

**Issue by pruizf** [dracor-org/dracor-schema#18]
This is a need that came up in the context of the Alsatian corpus. One of the authors (Paul Clemens) usually adds, after the _Dramatis Personae_, a separate list where additional details about the characters are given (these can include for instance age, appearance, costumes).

In _Chrischtowe_ (a Weihnachtsmärchen we just encoded), we've encoded this information in a `<list>` element inside a div in the `<front>`, which is valid in TEI-All. However, this does not validate against the DraCor schema. 

I was wondering if this possibility could be added to the DraCor schema, as perhaps other authors also use such a convention? If it cannot be added, which way would you suggest this type of information be encoded for compliance with the schema?

An example of these lists can be seen at this address: https://www.numistral.fr/ark:/12148/bpt6k91095403/f6.image.r=chrischtowe%20chrischtowe

However most full-length plays by this author follow the same pattern. By "full-length plays" I mean that his short comedy speeches ("komischer Vortrag") or his solo scenes do not use this convention.

**Comment by lehkost** [comment]
Yes, I think we could just allow this in our schema (@ingoboerner).

In similar cases in GerDraCor and RusDraCor, I think we just used ```<p>``` to encode this additional kind of information. Since we weren't really building critical editions from the ground up, we didn't put much effort into things we wouldn't eventually extract, but made sure not to lose any text to be able to re-encode passages once we've made up our mind.

So this use case could be a good reason to include ```<list>``` inside a div within ```<front>```.

**Comment by lehkost** [comment]
We have looked into this and decided to not include this in the schema for now. The reason is that the way you encoded it doesn't add an additional semantic value (```<label>``` and ```<item>``` are not semantically linked to each other nor are there IDs for speakers).

In order to validate against the schema, I would propose to keep the ```<head>```, but to dissolve the pairs of ```<label>``` and ```<item>``` to ```<p>```. Would that work for you? (We did so in the German corpus as well in such cases. We might re-evaluate this later, but for now there is no reason from the DraCor point of view to validate this markup.)
